### ISSUE TITLE
Database prefix misssing in migration

### ISSUE THREAD

**Issue by MartinSchillinger** [netresearch/module-shipping-core#3]
Hey,

there is an error in your migrations i.e. Netresearch\ShippingCore\Setup\Patch\Data\MigrateConfigPatch.
If Magento has been installed with a database prefix the setup:upgrade command will fail because the migrations cannot find the correct tables.

Best regards.

**Comment by mam08ixo** [comment]
Thank you for the report. We have a fix in place and will publish it soon.

**Comment by mam08ixo** [comment]
Running `composer update --with-dependencies dhl/shipping-m2` should pull in the `netresearch/module-shipping-core:2.2.1` dependency that considers table prefixes. Thanks.

**Comment by MartinSchillinger** [comment]
Thank you :-)
